PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS charities(id INTEGER PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, event TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', charity_id INTEGER REFERENCES charities(id), percentage INTEGER NOT NULL DEFAULT 10 CHECK(percentage BETWEEN 10 AND 80), plan TEXT, expires TEXT, cancelled INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS scores(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), score INTEGER NOT NULL CHECK(score BETWEEN 1 AND 45), date TEXT NOT NULL, UNIQUE(user_id,date));
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), charity_id INTEGER REFERENCES charities(id), kind TEXT NOT NULL, amount INTEGER NOT NULL, charity_amount INTEGER NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS draws(id INTEGER PRIMARY KEY, month TEXT NOT NULL UNIQUE, mode TEXT NOT NULL, numbers TEXT NOT NULL, pool INTEGER NOT NULL, rollover_in INTEGER NOT NULL, rollover_out INTEGER NOT NULL, entrants TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS winners(id INTEGER PRIMARY KEY, draw_id INTEGER NOT NULL REFERENCES draws(id), user_id INTEGER NOT NULL REFERENCES users(id), matches INTEGER NOT NULL, amount INTEGER NOT NULL, proof TEXT, review TEXT NOT NULL DEFAULT 'awaiting proof', status TEXT NOT NULL DEFAULT 'pending');
CREATE INDEX IF NOT EXISTS scores_user_date ON scores(user_id,date DESC);
CREATE INDEX IF NOT EXISTS winners_user ON winners(user_id);
CREATE TABLE IF NOT EXISTS simulations(id TEXT PRIMARY KEY, month TEXT NOT NULL, mode TEXT NOT NULL, numbers TEXT NOT NULL, fingerprint TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS billing_customers(user_id INTEGER PRIMARY KEY REFERENCES users(id), customer_id TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS billing_subscriptions(subscription_id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), customer_id TEXT NOT NULL, status TEXT NOT NULL, price_id TEXT NOT NULL, plan TEXT NOT NULL, paid_until TEXT, cancel_at_period_end INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS billing_subscriptions_user ON billing_subscriptions(user_id);
CREATE TABLE IF NOT EXISTS billing_orders(id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), kind TEXT NOT NULL, plan TEXT, charity_id INTEGER NOT NULL REFERENCES charities(id), percentage INTEGER NOT NULL, amount INTEGER NOT NULL, currency TEXT NOT NULL, price_id TEXT, session_id TEXT UNIQUE, status TEXT NOT NULL DEFAULT 'creating', created INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS billing_open_membership ON billing_orders(user_id) WHERE kind='subscription' AND status IN ('creating','open');
CREATE TABLE IF NOT EXISTS billing_events(id TEXT PRIMARY KEY, type TEXT NOT NULL, processed TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS billing_receipts(reference TEXT PRIMARY KEY, payment_id INTEGER UNIQUE NOT NULL REFERENCES payments(id), subscription_id TEXT, currency TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS billing_preferences(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), charity_id INTEGER NOT NULL REFERENCES charities(id), percentage INTEGER NOT NULL, effective INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS billing_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
