import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import Stripe from 'stripe';
import { billingConfig, createBilling } from '../billing.mjs';
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
 db.prepare('INSERT INTO charities(id,name,category,description) VALUES(1,?,?,?)').run('Test Cause','Education','Only for isolated automated tests.');
 db.prepare('INSERT INTO users(id,name,email,password,charity_id) VALUES(1,?,?,?,1)').run('Test Member','test@example.test','unused');
 const config={secretKey:'sk_test_fixture',webhookSecret:'whsec_fixture',origin:'http://127.0.0.1:4173',currency:'usd',monthly:1900,yearly:19000,monthlyPrice:'price_month',yearlyPrice:'price_year',portalConfiguration:'bpc_fixture'};
 const requests=[],sessions=new Map(),subs=new Map(),invoices=new Map();let creations=0;
 const realStripe=new Stripe('sk_test_fixture');
 const fake={webhooks:realStripe.webhooks,customers:{create:async()=>({id:'cus_fixture'})},prices:{retrieve:async id=>({id,active:true,livemode:false,currency:'usd',unit_amount:id==='price_month'?1900:19000,type:'recurring',recurring:{interval:id==='price_month'?'month':'year',interval_count:1,usage_type:'licensed'}})},checkout:{sessions:{create:async(params,opts)=>{requests.push({params,opts});const id='cs_'+(++creations);const session={...params,id,livemode:false,status:'open',url:'https://checkout.stripe.com/c/pay/'+id,created:Math.floor(Date.now()/1000)};sessions.set(id,session);return session;},retrieve:async id=>sessions.get(id),expire:async id=>{sessions.get(id).status='expired';}}},subscriptions:{retrieve:async id=>subs.get(id)},invoices:{retrieve:async id=>invoices.get(id)},billingPortal:{sessions:{create:async()=>({url:'https://billing.stripe.com/p/session_fixture'})}}};
 const billing=createBilling({db,config,stripe:fake});const user=db.prepare('SELECT * FROM users WHERE id=1').get();
 const event=(type,object,id='evt_'+Math.random())=>({id,type,livemode:false,data:{object}});
 async function invoiceSetup(){await billing.checkout(user,{kind:'subscription',plan:'monthly'});const session=sessions.get('cs_1');const end=Math.floor(Date.now()/1000)+864000;
 const sub={id:'sub_1',customer:'cus_fixture',livemode:false,status:'active',metadata:session.metadata,cancel_at_period_end:false,items:{data:[{quantity:1,price:{id:'price_month'}}]}};subs.set(sub.id,sub);
 const invoice={id:'in_1',status:'paid',amount_paid:1900,currency:'usd',livemode:false,customer:'cus_fixture',created:Math.floor(Date.now()/1000),parent:{subscription_details:{subscription:sub.id}},lines:{data:[{quantity:1,pricing:{price_details:{price:'price_month'}},period:{end}}]}};invoices.set(invoice.id,invoice);return {sub,invoice,session};}
 return {db,billing,user,event,requests,sessions,subs,invoices,invoiceSetup,config,realStripe};
}
test('live keys require HTTPS and config excludes redirect paths',()=>{assert.throws(()=>billingConfig({STRIPE_SECRET_KEY:'sk_live_example',APP_URL:'http://example.com'}));assert.throws(()=>billingConfig({APP_URL:'https://example.com/redirect'}));});
test('checkout creates an actual provider session, not an active member; duplicate clicks reuse it',async()=>{const f=fixture();const a=await f.billing.checkout(f.user,{kind:'subscription',plan:'monthly'});const b=await f.billing.checkout(f.user,{kind:'subscription',plan:'monthly'});assert.equal(a.url,b.url);assert.equal(f.requests.length,1);assert.equal(f.requests[0].params.line_items[0].price,'price_month');assert.equal(f.billing.membership(1).active,false);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,0);f.db.close();});
test('price changes expire stale checkouts rather than charging the old plan',async()=>{const f=fixture();await f.billing.checkout(f.user,{kind:'subscription',plan:'monthly'});await f.billing.checkout(f.user,{kind:'subscription',plan:'yearly'});assert.equal(f.sessions.get('cs_1').status,'expired');assert.equal(f.requests[1].params.line_items[0].price,'price_year');f.db.close();});
test('unpaid completed checkout does not activate membership',async()=>{const f=fixture();const {session,sub}=await f.invoiceSetup();session.mode='subscription';session.subscription=sub.id;session.status='complete';session.payment_status='unpaid';await f.billing.processEvent(f.event('checkout.session.completed',session));assert.equal(f.billing.membership(1).active,false);f.db.close();});
test('paid invoice enables access, records charity once, and tolerates duplicate event IDs and different retry IDs',async()=>{const f=fixture();const {invoice}=await f.invoiceSetup();const event=f.event('invoice.paid',invoice,'evt_paid');await f.billing.processEvent(event);await f.billing.processEvent(event);await f.billing.processEvent({...event,id:'evt_paid_duplicate'});assert.equal(f.billing.membership(1).active,true);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,1);assert.equal(f.db.prepare('SELECT charity_amount FROM payments').get().charity_amount,190);f.db.close();});
test('renewal extends access; out-of-order old invoices never reduce expiry',async()=>{const f=fixture();const {invoice}=await f.invoiceSetup();await f.billing.processEvent(f.event('invoice.paid',invoice));const next=structuredClone(invoice);next.id='in_2';next.lines.data[0].period.end+=30*86400;f.invoices.set(next.id,next);await f.billing.processEvent(f.event('invoice.paid',next));const end=f.billing.membership(1).expires;await f.billing.processEvent(f.event('invoice.paid',invoice));assert.equal(f.billing.membership(1).expires,end);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,2);f.db.close();});
test('failed payment/cancelled subscriptions revoke access; stale events retrieve current state',async()=>{const f=fixture();const {invoice,sub}=await f.invoiceSetup();await f.billing.processEvent(f.event('invoice.paid',invoice));sub.cancel_at_period_end=true;await f.billing.processEvent(f.event('customer.subscription.updated',sub));assert.equal(f.billing.membership(1).active,true);assert.equal(f.billing.membership(1).cancelled,1);sub.status='past_due';await f.billing.processEvent(f.event('invoice.payment_failed',invoice));assert.equal(f.billing.membership(1).active,false);sub.status='canceled';await f.billing.processEvent(f.event('customer.subscription.updated',{...sub,status:'active'}));assert.equal(f.billing.membership(1).active,false);f.db.close();});
test('wrong amount, currency, price and customer cannot activate access',async()=>{for(const mutation of [i=>i.amount_paid=1,i=>i.currency='gbp',i=>i.customer='cus_other',i=>i.lines.data[0].pricing.price_details.price='price_other']){const f=fixture();const {invoice}=await f.invoiceSetup();mutation(invoice);await assert.rejects(f.billing.processEvent(f.event('invoice.paid',invoice)));assert.equal(f.billing.membership(1).active,false);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,0);f.db.close();}});
test('donation ledger is written only after verified successful payment',async()=>{const f=fixture();await f.billing.checkout(f.user,{kind:'donation',amount:2500,charity_id:1});const s=f.sessions.get('cs_1');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,0);Object.assign(s,{payment_status:'paid',currency:'usd',amount_total:2500,status:'complete'});await f.billing.processEvent(f.event('checkout.session.completed',s));await f.billing.processEvent(f.event('checkout.session.async_payment_succeeded',s));assert.equal(f.db.prepare('SELECT charity_amount FROM payments').get().charity_amount,2500);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM payments').get().n,1);assert.equal(f.billing.membership(1).active,false);f.db.close();});
test('official signature verification rejects tampering, stale signatures and wrong mode',async()=>{const f=fixture();const payload=JSON.stringify(f.event('unhandled.event',{id:'obj'},'evt_sig'));const header=f.realStripe.webhooks.generateTestHeaderString({payload,secret:f.config.webhookSecret});await f.billing.webhook(Buffer.from(payload),header);await assert.rejects(f.billing.webhook(Buffer.from(payload+' '),header));const stale=f.realStripe.webhooks.generateTestHeaderString({payload,secret:f.config.webhookSecret,timestamp:1});await assert.rejects(f.billing.webhook(Buffer.from(payload),stale));await assert.rejects(f.billing.processEvent({...JSON.parse(payload),livemode:true,id:'evt_live'}));f.db.close();});
